# Data source: Internet Archive ChinaXiv mirror
internet_archive:
  collection: "chinaxivmirror"
  base_url: "https://archive.org"
  scrape_endpoint: "/services/search/v1/scrape"
  metadata_endpoint: "/metadata"
  download_endpoint: "/download"
  batch_size: 10000  # Max items per API call
  min_year: 2017  # Filter for papers >= this year (Attention Is All You Need: June 2017)

# DEPRECATED: OAI-PMH endpoint blocked by bot detection
# oai:
#   base_url: "https://chinaxiv.org/oai/OAIHandler"  # BLOCKED - do not use
#   sets: []  # e.g., ["physics:astro-ph"]
#   metadata_prefix: "oai_eprint"
#   date_window_days: 1

# DEPRECATED: Proxy not needed with Internet Archive
# proxy:
#   enabled: false  # Set to true to use proxy
#   http: "http://127.0.0.1:1087"  # Example: local proxy
#   https: "http://127.0.0.1:1087"  # Or use SOCKS: "socks5://127.0.0.1:1080"
#   # Alternatively, set env vars: HTTP_PROXY, HTTPS_PROXY, or SOCKS5_PROXY

models:
  default_slug: "deepseek/deepseek-v3.2-exp"
  alternates:
    - "z-ai/glm-4.5-air"

glossary:
  - zh: "机器学习"
    en: "machine learning"
  - zh: "深度学习"
    en: "deep learning"

# DISABLED: We do not care about licenses. All papers translated in full.
# license_mappings:
#   CC-BY: { derivatives_allowed: true, badge: "CC BY" }
#   CC BY: { derivatives_allowed: true, badge: "CC BY" }
#   CC-BY-SA: { derivatives_allowed: true, badge: "CC BY-SA" }
#   CC BY-SA: { derivatives_allowed: true, badge: "CC BY-SA" }
#   CC-BY-ND: { derivatives_allowed: false, badge: "CC BY-ND" }
#   CC BY-ND: { derivatives_allowed: false, badge: "CC BY-ND" }
#   CC0: { derivatives_allowed: true, badge: "CC0" }
#   Public Domain: { derivatives_allowed: true, badge: "Public Domain" }

cost:
  pricing_per_mtoken:
    deepseek/deepseek-v3.2-exp: { input: 0.27, output: 0.40 }
    z-ai/glm-4.5-air: { input: 0.14, output: 0.86 }
