data_source:
  mode: "manual"  # 'manual' or 'custom' (external harvester). Internet Archive removed.

# Optional proxy configuration (for custom harvesters or PDF fetches)
proxy:
  enabled: false
  http: "http://127.0.0.1:1087"
  https: "http://127.0.0.1:1087"

models:
  default_slug: "deepseek/deepseek-v3.2-exp"
  alternates:
    - "z-ai/glm-4.5-air"
translation:
  batch_paragraphs: false
  retry_chinese_chars: true  # Enable retry for Chinese characters

formatting:
  # model: deepseek/deepseek-v3.2-exp  # optional override
  temperature: 0.1

glossary:
  - zh: "机器学习"
    en: "machine learning"
  - zh: "深度学习"
    en: "deep learning"

validation_thresholds:
  harvest:
    min_schema_rate: 95.0
    min_pdf_rate: 98.0
  ocr:
    min_char_gain: 500
    min_multiplier: 5.0
    min_pass_rate: 98.0
    min_alpha_ratio: 0.05
    max_most_common_ratio: 0.6
  translation:
    max_flagged_ratio: 0.05  # Allow up to 5% of translations to be flagged before failing
    max_flagged_absolute: 10
  pdf_detection:
    min_char_threshold: 1500

# DISABLED: We do not care about licenses. All papers translated in full.
# license_mappings:
#   CC-BY: { derivatives_allowed: true, badge: "CC BY" }
#   CC BY: { derivatives_allowed: true, badge: "CC BY" }
#   CC-BY-SA: { derivatives_allowed: true, badge: "CC BY-SA" }
#   CC BY-SA: { derivatives_allowed: true, badge: "CC BY-SA" }
#   CC-BY-ND: { derivatives_allowed: false, badge: "CC BY-ND" }
#   CC BY-ND: { derivatives_allowed: false, badge: "CC BY-ND" }
#   CC0: { derivatives_allowed: true, badge: "CC0" }
#   Public Domain: { derivatives_allowed: true, badge: "Public Domain" }

cost:
  pricing_per_mtoken:
    deepseek/deepseek-v3.2-exp: { input: 0.27, output: 0.40 }
    z-ai/glm-4.5-air: { input: 0.14, output: 0.86 }
