# Test batch workflow with inputs
name: Batch Test

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Papers per batch'
        required: false
        default: '50'

jobs:
  test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Batch size: ${{ github.event.inputs.batch_size }}"
