name: Harvest Validation Gate

on:
  workflow_dispatch:
    inputs:
      records_path:
        description: "Path to records JSON (optional)"
        required: false

jobs:
  gate:
    uses: ./.github/workflows/validation-gate.yml
    with:
      gate_id: harvest
      pre_command: |
        python scripts/prepare_gate_fixtures.py
      command: |
        set -e
        if [ -n "$RECORDS_PATH" ]; then
          python -m src.validators.harvest_gate --records "$RECORDS_PATH"
        else
          python -m src.validators.harvest_gate
        fi
      records_path: ${{ github.event.inputs.records_path || '' }}
      artifact_name: harvest-report-${{ github.run_id }}
      artifact_paths: |
        reports/harvest_report.json
        reports/harvest_report.md
      artifact_if_missing: error
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
      brightdata_api_key: ${{ secrets.BRIGHTDATA_API_KEY }}
      brightdata_zone: ${{ secrets.BRIGHTDATA_ZONE }}
