name: OCR Validation Gate

on:
  workflow_dispatch: {}

jobs:
  gate:
    uses: ./.github/workflows/validation-gate.yml
    with:
      gate_id: ocr
      command: |
        set -e
        python -m src.validators.ocr_gate
      artifact_name: ocr-gate-report-${{ github.run_id }}
      artifact_paths: |
        reports/ocr_gate_report.json
        reports/ocr_gate_report.md
      artifact_if_missing: error
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
      brightdata_api_key: ${{ secrets.BRIGHTDATA_API_KEY }}
      brightdata_zone: ${{ secrets.BRIGHTDATA_ZONE }}
