name: Preflight Validation

on:
  workflow_dispatch: {}

jobs:
  preflight:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            tesseract-ocr \
            tesseract-ocr-chi-sim \
            tesseract-ocr-chi-tra \
            ghostscript \
            pngquant \
            qpdf \
            unpaper

      - name: Run preflight checks and generate reports
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          BRIGHTDATA_API_KEY: ${{ secrets.BRIGHTDATA_API_KEY }}
          BRIGHTDATA_ZONE: ${{ secrets.BRIGHTDATA_ZONE }}
        run: |
          set -e
          python -m src.tools.env_diagnose --preflight
          
      - name: Upload preflight report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: preflight-report-${{ github.run_id }}
          path: |
            reports/preflight_report.json
            reports/preflight_report.md
          if-no-files-found: ignore
