name: Preflight Validation

on:
  workflow_dispatch: {}

jobs:
  preflight:
    uses: ./.github/workflows/validation-gate.yml
    with:
      gate_id: preflight
      command: |
        set -e
        python -m src.tools.env_diagnose --preflight
      artifact_name: preflight-report-${{ github.run_id }}
      artifact_paths: |
        reports/preflight_report.json
        reports/preflight_report.md
      artifact_if_missing: ignore
      timeout_minutes: 30
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
      brightdata_api_key: ${{ secrets.BRIGHTDATA_API_KEY }}
      brightdata_zone: ${{ secrets.BRIGHTDATA_ZONE }}
