name: Preflight Validation

on:
  workflow_dispatch: {}

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run preflight checks and generate reports
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          BRIGHTDATA_API_KEY: ${{ secrets.BRIGHTDATA_API_KEY }}
          BRIGHTDATA_ZONE: ${{ secrets.BRIGHTDATA_ZONE }}
        run: |
          set -e
          python -m src.tools.env_diagnose --preflight
      - name: Upload preflight report
        uses: actions/upload-artifact@v4
        with:
          name: preflight-report-${{ github.run_id }}
          path: |
            reports/preflight_report.json
            reports/preflight_report.md
          if-no-files-found: error

