name: Real E2E Tests

on:
  workflow_dispatch:
    inputs:
      test_category:
        description: 'Test category to run'
        required: true
        default: 'quality'
        type: choice
        options:
        - quality
        - batch
        - pipeline
        - all
      papers_limit:
        description: 'Maximum papers to process'
        required: false
        default: '5'
        type: string

jobs:
  real-e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check requirements
      run: |
        python scripts/run_real_e2e_tests.py --check-only
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        
    - name: Run Real E2E Tests
      run: |
        python scripts/run_real_e2e_tests.py --category ${{ github.event.inputs.test_category }} --limit ${{ github.event.inputs.papers_limit }}
      env:
        OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        RUN_REAL_E2E: "1"
        
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: real-e2e-test-results
        path: |
          data/translated/
          site/
        retention-days: 7
        
    - name: Notify Discord
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Real E2E tests passed for ${{ github.event.inputs.test_category }}"
        else
          echo "❌ Real E2E tests failed for ${{ github.event.inputs.test_category }}"
        fi
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
