name: Translation Validation Gate

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Papers per batch'
        required: false
        default: '100'
      workers:
        description: 'Parallel workers'
        required: false
        default: '20'
      matrix_index:
        description: 'Matrix job index'
        required: false
        default: '0'

jobs:
  gate:
    uses: ./.github/workflows/validation-gate.yml
    with:
      gate_id: translation
      pre_command: |
        python scripts/prepare_gate_fixtures.py
      command: |
        set -e
        python -m src.validators.translation_gate
      artifact_name: translation-report-${{ github.event.inputs.matrix_index || '0' }}
      artifact_paths: reports/translation_report.json
      artifact_if_missing: ignore
      timeout_minutes: 180
    secrets:
      openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
      brightdata_api_key: ${{ secrets.BRIGHTDATA_API_KEY }}
      brightdata_zone: ${{ secrets.BRIGHTDATA_ZONE }}
